apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
      - name: admin
        image: "{{ .Values.global.imageRegistry }}/admin:{{ .Values.global.imageTag }}"
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: plane-vault-secret
---
apiVersion: v1
kind: Service
metadata:
  name: admin
spec:
  selector:
    app: admin
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
