apiVersion: batch/v1
kind: Job
metadata:
  name: migrator-{{ randAlphaNum 5 | lower }}
  annotations:
    "helm.sh/hook": pre-upgrade,pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      containers:
      - name: migrator
        image: "{{ .Values.global.imageRegistry }}/migrator:{{ .Values.global.imageTag }}"
        command: ["./bin/docker-entrypoint-migrator.sh"]
        envFrom:
        - secretRef:
            name: plane-vault-secret
      restartPolicy: Never
